# enable gui
$gui = true

# ------------------------------------------------------------
# Description
# ------------------------------------------------------------
$description = <<"EOS"
# Cumulus Linux test

user: vagrant
password: vagrant
EOS


# ------------------------------------------------------------
# vagrant configure version 2
# ------------------------------------------------------------
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vbguest.auto_update = false

    # ssh config
    # config.ssh.username = 'vagrant'
    # config.ssh.password = 'vagrant'
    # config.ssh.insert_key = false

    # 
    # Cumulus Linux
    # ------------------------------------------------------------
    sonic1 = "sonic1"
    config.vm.define sonic1 do |switch|
        # switch.vm.hostname = sonic1  ## error!
        switch.vm.box = "./sonic-vs.box"

        switch.ssh.username = 'admin'
        switch.ssh.password = 'YourPaSsWoRd'
        switch.ssh.insert_key = false

        switch.vm.provision "shell", inline: "hostname " + sonic1

        switch.vm.synced_folder '.', '/vagrant', disabled: true

        # private network config
        # switch.vm.network "private_network", virtualbox__intnet: "net1", auto_config: false
        # switch.vm.network "private_network", virtualbox__intnet: "net2", auto_config: false

        # # set network config
        # switch.vm.provision "shell", inline: $daemons
        # switch.vm.provision "shell", inline: to_vtysh_cmd($sonic1_conf)

        # virtual box config
        switch.vm.provider "virtualbox" do |vb|
            vb.name = sonic1
            vb.gui = $gui
            vb.cpus = 2
            vb.memory = 2048
            vb.customize [
                "modifyvm", :id,
                "--vram", "16", 
                "--clipboard", "bidirectional",
                "--draganddrop", "bidirectional",
                "--ioapic", "on",
                "--graphicscontroller", "vmsvga",
                "--accelerate3d", "off",
                "--hwvirtex", "on",
                "--nestedpaging", "on",
                "--largepages", "on",
                "--pae", "on",
                "--audio", "none",
                "--chipset", "ich9",
                "--description", $description
            ]

            (1..switch.vm.networks.count {|nw| !nw.include? :forwarded_port}).each do |i|
                vb.customize ["modifyvm", :id, "--nicpromisc#{i+1}", "allow-all"]
            end
        end
    end
end
