# enable gui
$gui = true

# ------------------------------------------------------------
# Description
# ------------------------------------------------------------
$description = <<"EOS"
# Cumulus and SONiC

## Cumulus
user: vagrant
password: vagrant

## SONiC
user: admin
password: YourPaSsWoRd
EOS

# ------------------------------------------------------------
# FRRouting Config
# ------------------------------------------------------------
$reset_sonic = <<-'SCRIPT'
sudo cat <<'EOF' | sudo tee /etc/sonic/config_db.json
{
  "DEVICE_METADATA": {
      "localhost": {
          "hwsku": "Force10-S6000",
          "platform": "x86_64-kvm_x86_64-r0",
          "mac": "08:00:27:f6:18:74",
          "hostname": "%{hostname}",
          "type": "LeafRouter"
      }
  },
  "PORT": {
      "Ethernet0": {
          "lanes": "25,26,27,28",
          "alias": "fortyGigE0/0",
          "index": "0",
          "speed": "40000",
          "admin_status": "up",
          "mtu": "9100"
      },
      "Ethernet4": {
          "lanes": "29,30,31,32",
          "alias": "fortyGigE0/4",
          "index": "1",
          "speed": "40000",
          "admin_status": "up",
          "mtu": "9100"
      },
      "Ethernet8": {
          "lanes": "33,34,35,36",
          "alias": "fortyGigE0/8",
          "index": "2",
          "speed": "40000",
          "admin_status": "up",
          "mtu": "9100"
      },
      "Ethernet12": {
          "lanes": "37,38,39,40",
          "alias": "fortyGigE0/12",
          "index": "3",
          "speed": "40000",
          "admin_status": "up",
          "mtu": "9100"
      },
      "Ethernet16": {
          "lanes": "45,46,47,48",
          "alias": "fortyGigE0/16",
          "index": "4",
          "speed": "40000",
          "admin_status": "up",
          "mtu": "9100"
      },
      "Ethernet20": {
          "lanes": "41,42,43,44",
          "alias": "fortyGigE0/20",
          "index": "5",
          "speed": "40000",
          "admin_status": "up",
          "mtu": "9100"
      },
      "Ethernet24": {
          "lanes": "1,2,3,4",
          "alias": "fortyGigE0/24",
          "index": "6",
          "speed": "40000",
          "admin_status": "up",
          "mtu": "9100"
      },
      "Ethernet28": {
          "lanes": "5,6,7,8",
          "alias": "fortyGigE0/28",
          "index": "7",
          "speed": "40000",
          "admin_status": "up",
          "mtu": "9100"
      },
      "Ethernet32": {
          "lanes": "13,14,15,16",
          "alias": "fortyGigE0/32",
          "index": "8",
          "speed": "40000",
          "admin_status": "up",
          "mtu": "9100"
      },
      "Ethernet36": {
          "lanes": "9,10,11,12",
          "alias": "fortyGigE0/36",
          "index": "9",
          "speed": "40000",
          "admin_status": "up",
          "mtu": "9100"
      },
      "Ethernet40": {
          "lanes": "17,18,19,20",
          "alias": "fortyGigE0/40",
          "index": "10",
          "speed": "40000",
          "admin_status": "up",
          "mtu": "9100"
      },
      "Ethernet44": {
          "lanes": "21,22,23,24",
          "alias": "fortyGigE0/44",
          "index": "11",
          "speed": "40000",
          "admin_status": "up",
          "mtu": "9100"
      },
      "Ethernet48": {
          "lanes": "53,54,55,56",
          "alias": "fortyGigE0/48",
          "index": "12",
          "speed": "40000",
          "admin_status": "up",
          "mtu": "9100"
      },
      "Ethernet52": {
          "lanes": "49,50,51,52",
          "alias": "fortyGigE0/52",
          "index": "13",
          "speed": "40000",
          "admin_status": "up",
          "mtu": "9100"
      },
      "Ethernet56": {
          "lanes": "57,58,59,60",
          "alias": "fortyGigE0/56",
          "index": "14",
          "speed": "40000",
          "admin_status": "up",
          "mtu": "9100"
      },
      "Ethernet60": {
          "lanes": "61,62,63,64",
          "alias": "fortyGigE0/60",
          "index": "15",
          "speed": "40000",
          "admin_status": "up",
          "mtu": "9100"
      },
      "Ethernet64": {
          "lanes": "69,70,71,72",
          "alias": "fortyGigE0/64",
          "index": "16",
          "speed": "40000",
          "admin_status": "up",
          "mtu": "9100"
      },
      "Ethernet68": {
          "lanes": "65,66,67,68",
          "alias": "fortyGigE0/68",
          "index": "17",
          "speed": "40000",
          "admin_status": "up",
          "mtu": "9100"
      },
      "Ethernet72": {
          "lanes": "73,74,75,76",
          "alias": "fortyGigE0/72",
          "index": "18",
          "speed": "40000",
          "admin_status": "up",
          "mtu": "9100"
      },
      "Ethernet76": {
          "lanes": "77,78,79,80",
          "alias": "fortyGigE0/76",
          "index": "19",
          "speed": "40000",
          "admin_status": "up",
          "mtu": "9100"
      },
      "Ethernet80": {
          "lanes": "109,110,111,112",
          "alias": "fortyGigE0/80",
          "index": "20",
          "speed": "40000",
          "admin_status": "up",
          "mtu": "9100"
      },
      "Ethernet84": {
          "lanes": "105,106,107,108",
          "alias": "fortyGigE0/84",
          "index": "21",
          "speed": "40000",
          "admin_status": "up",
          "mtu": "9100"
      },
      "Ethernet88": {
          "lanes": "113,114,115,116",
          "alias": "fortyGigE0/88",
          "index": "22",
          "speed": "40000",
          "admin_status": "up",
          "mtu": "9100"
      },
      "Ethernet92": {
          "lanes": "117,118,119,120",
          "alias": "fortyGigE0/92",
          "index": "23",
          "speed": "40000",
          "admin_status": "up",
          "mtu": "9100"
      },
      "Ethernet96": {
          "lanes": "125,126,127,128",
          "alias": "fortyGigE0/96",
          "index": "24",
          "speed": "40000",
          "admin_status": "up",
          "mtu": "9100"
      },
      "Ethernet100": {
          "lanes": "121,122,123,124",
          "alias": "fortyGigE0/100",
          "index": "25",
          "speed": "40000",
          "admin_status": "up",
          "mtu": "9100"
      },
      "Ethernet104": {
          "lanes": "81,82,83,84",
          "alias": "fortyGigE0/104",
          "index": "26",
          "speed": "40000",
          "admin_status": "up",
          "mtu": "9100"
      },
      "Ethernet108": {
          "lanes": "85,86,87,88",
          "alias": "fortyGigE0/108",
          "index": "27",
          "speed": "40000",
          "admin_status": "up",
          "mtu": "9100"
      },
      "Ethernet112": {
          "lanes": "93,94,95,96",
          "alias": "fortyGigE0/112",
          "index": "28",
          "speed": "40000",
          "admin_status": "up",
          "mtu": "9100"
      },
      "Ethernet116": {
          "lanes": "89,90,91,92",
          "alias": "fortyGigE0/116",
          "index": "29",
          "speed": "40000",
          "admin_status": "up",
          "mtu": "9100"
      },
      "Ethernet120": {
          "lanes": "101,102,103,104",
          "alias": "fortyGigE0/120",
          "index": "30",
          "speed": "40000",
          "admin_status": "up",
          "mtu": "9100"
      },
      "Ethernet124": {
          "lanes": "97,98,99,100",
          "alias": "fortyGigE0/124",
          "index": "31",
          "speed": "40000",
          "admin_status": "up",
          "mtu": "9100"
      }
  },
  "FLEX_COUNTER_TABLE": {
      "ACL": {
          "FLEX_COUNTER_STATUS": "disable",
          "FLEX_COUNTER_DELAY_STATUS": "true",
          "POLL_INTERVAL": "10000"
      }
  },
  "LOOPBACK_INTERFACE": {
      "Loopback0|10.1.0.1/32": {}
  },
  "INTERFACE": {
    "Ethernet0": {},
    "Ethernet4": {},
    "Ethernet8": {},
    "Ethernet12": {},
    "Ethernet16": {},
    "Ethernet20": {},
    "Ethernet24": {},
    "Ethernet28": {},
    "Ethernet32": {},
    "Ethernet36": {},
    "Ethernet40": {},
    "Ethernet44": {},
    "Ethernet48": {},
    "Ethernet52": {},
    "Ethernet56": {},
    "Ethernet60": {},
    "Ethernet64": {},
    "Ethernet68": {},
    "Ethernet72": {},
    "Ethernet76": {},
    "Ethernet80": {},
    "Ethernet84": {},
    "Ethernet88": {},
    "Ethernet92": {},
    "Ethernet96": {},
    "Ethernet100": {},
    "Ethernet104": {},
    "Ethernet108": {},
    "Ethernet112": {},
    "Ethernet116": {},
    "Ethernet120": {},
    "Ethernet124": {}
  }
}
EOF

# 起動待ち
sleep 4m
sudo config reload -y

# 起動待ち
sleep 2m
SCRIPT

$daemons = <<-'SCRIPT'
cat << 'EOF' | tee /etc/frr/daemons
zebra=yes
bgpd=yes
ospfd=no
ospf6d=no
ripd=no
ripngd=no
isisd=no
fabricd=no
pimd=no
ldpd=no
nhrpd=no
eigrpd=no
babeld=no
sharpd=no
pbrd=no
fabricd=no
vrrpd=no

vtysh_enable=yes
zebra_options="  -M cumulus_mlag -M snmp -A 127.0.0.1 -s 90000000"
bgpd_options="   -M snmp -A 127.0.0.1"
ospfd_options="  -M snmp -A 127.0.0.1"
ospf6d_options=" -M snmp -A ::1"
ripd_options="   -A 127.0.0.1"
ripngd_options=" -A ::1"
isisd_options="  -A 127.0.0.1"
pimd_options="   -A 127.0.0.1"
ldpd_options="   -A 127.0.0.1"
nhrpd_options="  -A 127.0.0.1"
eigrpd_options=" -A 127.0.0.1"
babeld_options=" -A 127.0.0.1"
sharpd_options=" -A 127.0.0.1"
pbrd_options="   -A 127.0.0.1"
staticd_options="-A 127.0.0.1"
fabricd_options="-A 127.0.0.1"
vrrpd_options="  -A 127.0.0.1"
EOF

systemctl restart frr
SCRIPT

$spine1_conf = <<-'CONFIG'
enable
configure terminal
interface lo
  ip address 10.0.0.1/32
interface Ethernet0
  ip address 10.1.0.1/24
  ipv6 nd ra-interval 10
  no ipv6 nd suppress-ra
  no shut
interface Ethernet4
  ip address 10.2.0.1/24
  ipv6 nd ra-interval 10
  no ipv6 nd suppress-ra
  no shut

router bgp 65200
  bgp router-id 10.0.0.1
  no bgp ebgp-requires-policy
  bgp bestpath as-path multipath-relax
  neighbor FABRIC peer-group
  neighbor FABRIC remote-as external
  neighbor FABRIC capability extended-nexthop
  neighbor Ethernet0 interface peer-group FABRIC
  neighbor Ethernet4 interface peer-group FABRIC
  address-family ipv4 unicast
    network 10.0.0.1/32
  exit-address-family
end
write mem
CONFIG

$leaf1_conf = <<-'CONFIG'
enable
configure terminal
interface lo
  ip address 10.0.1.1/32
interface swp1
  ip address 10.1.0.2/24
  ipv6 nd ra-interval 10
  no ipv6 nd suppress-ra
  no shut
interface swp2
  ip address 192.168.1.1/24
  no shut

router bgp 65100
  bgp router-id 10.0.1.1
  no bgp ebgp-requires-policy
  bgp bestpath as-path multipath-relax
  neighbor FABRIC peer-group
  neighbor FABRIC remote-as external
  neighbor FABRIC capability extended-nexthop
  neighbor swp1 interface peer-group FABRIC
  neighbor swp2 interface peer-group FABRIC
  address-family ipv4 unicast
    network 10.0.1.1/32
    network 192.168.1.1/24
  exit-address-family

end
write mem
CONFIG

$leaf2_conf = <<-'CONFIG'
enable
configure terminal
interface lo
  ip address 10.0.1.2/32
interface swp1
  ip address 10.2.0.2/24
  ipv6 nd ra-interval 10
  no ipv6 nd suppress-ra
  no shut
interface swp2
  ip address 192.168.2.1/24
  no shut

router bgp 65101
  bgp router-id 10.0.1.2
  no bgp ebgp-requires-policy
  bgp bestpath as-path multipath-relax
  neighbor FABRIC peer-group
  neighbor FABRIC remote-as external
  neighbor FABRIC capability extended-nexthop
  neighbor swp1 interface peer-group FABRIC
  neighbor swp2 interface peer-group FABRIC
  address-family ipv4 unicast
    network 10.0.1.2/32
    network 192.168.2.1/24
  exit-address-family

end
write mem
CONFIG


def to_vtysh_cmd(s)
    "vtysh" + s.split("\n").map{|s| " -c \"" + s + "\""}.join()
end

# ------------------------------------------------------------
# Host Config
# ------------------------------------------------------------
$host1_conf = <<-'SCRIPT'
ip link set eth1 up
ip address add 192.168.1.2/24 dev eth1
ip route add 192.168.2.0/24 via 192.168.1.1 dev eth1
SCRIPT

$host2_conf = <<-'SCRIPT'
ip link set eth1 up
ip address add 192.168.2.2/24 dev eth1
ip route add 192.168.1.0/24 via 192.168.2.1 dev eth1
SCRIPT


# ------------------------------------------------------------
# vagrant configure version 2
# ------------------------------------------------------------
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vbguest.auto_update = false

    # 
    # SONiC
    # ------------------------------------------------------------
    spine1 = "clos-spine1"
    config.vm.define spine1 do |switch|
        switch.vm.box = "sonic-vs"

        switch.ssh.username = 'admin'
        switch.ssh.password = 'YourPaSsWoRd'
        switch.ssh.insert_key = false

        switch.vm.boot_timeout = 18000
        switch.vm.synced_folder '.', '/vagrant', disabled: true

        # private network config
        switch.vm.network "private_network", virtualbox__intnet: "net1", auto_config: false
        switch.vm.network "private_network", virtualbox__intnet: "net2", auto_config: false

        # # set network config
        switch.vm.provision "shell", inline: $reset_sonic % {hostname: spine1}
        switch.vm.provision "shell", inline: to_vtysh_cmd($spine1_conf)

        # virtual box config
        switch.vm.provider "virtualbox" do |vb|
            vb.name = spine1
            vb.gui = $gui
            vb.cpus = 1
            vb.memory = 2048
            vb.customize [
                "modifyvm", :id,
                "--vram", "16", 
                "--clipboard", "bidirectional",
                "--draganddrop", "bidirectional",
                "--ioapic", "off",
                "--graphicscontroller", "vmsvga",
                "--accelerate3d", "off",
                "--hwvirtex", "on",
                "--nestedpaging", "on",
                "--largepages", "on",
                "--pae", "on",
                "--audio", "none",
                "--chipset", "piix3",
                "--uartmode1", "disconnected",
                "--description", $description
            ]

            (1..switch.vm.networks.count {|nw| !nw.include? :forwarded_port}).each do |i|
                vb.customize ["modifyvm", :id, "--nicpromisc#{i+1}", "allow-all"]
            end
        end
      end

    # 
    # Cumulus Linux
    # ------------------------------------------------------------
    leaf1 = "clos-leaf1"
    config.vm.define leaf1 do |switch|
        switch.vm.hostname = leaf1
        switch.vm.box = "CumulusCommunity/cumulus-vx"

        # private network config
        switch.vm.network "private_network", virtualbox__intnet: "net1", auto_config: false
        switch.vm.network "private_network", virtualbox__intnet: "net3", auto_config: false

        # set network config
        switch.vm.provision "shell", inline: $daemons
        switch.vm.provision "shell", inline: to_vtysh_cmd($leaf1_conf)

        # virtual box config
        switch.vm.provider "virtualbox" do |vb|
            vb.name = leaf1
            vb.gui = $gui
            vb.cpus = 1
            vb.memory = 1024
            vb.customize [
                "modifyvm", :id,
                "--vram", "16", 
                "--clipboard", "bidirectional",
                "--draganddrop", "bidirectional",
                "--ioapic", "on",
                "--graphicscontroller", "vmsvga",
                "--accelerate3d", "off",
                "--hwvirtex", "on",
                "--nestedpaging", "on",
                "--largepages", "on",
                "--pae", "on",
                "--audio", "none",
                "--chipset", "ich9",
                "--description", $description
            ]

            (1..switch.vm.networks.count {|nw| !nw.include? :forwarded_port}).each do |i|
                vb.customize ["modifyvm", :id, "--nicpromisc#{i+1}", "allow-all"]
            end
        end
    end

    leaf2 = "clos-leaf2"
    config.vm.define leaf2 do |switch|
        switch.vm.hostname = leaf2
        switch.vm.box = "CumulusCommunity/cumulus-vx"

        # private network config
        switch.vm.network "private_network", virtualbox__intnet: "net2", auto_config: false
        switch.vm.network "private_network", virtualbox__intnet: "net4", auto_config: false

        # set network config
        switch.vm.provision "shell", inline: $daemons
        switch.vm.provision "shell", inline: to_vtysh_cmd($leaf2_conf)

        # virtual box config
        switch.vm.provider "virtualbox" do |vb|
            vb.name = leaf2
            vb.gui = $gui
            vb.cpus = 1
            vb.memory = 1024
            vb.customize [
                "modifyvm", :id,
                "--vram", "16", 
                "--clipboard", "bidirectional",
                "--draganddrop", "bidirectional",
                "--ioapic", "on",
                "--graphicscontroller", "vmsvga",
                "--accelerate3d", "off",
                "--hwvirtex", "on",
                "--nestedpaging", "on",
                "--largepages", "on",
                "--pae", "on",
                "--audio", "none",
                "--chipset", "ich9",
                "--description", $description
            ]

            (1..switch.vm.networks.count {|nw| !nw.include? :forwarded_port}).each do |i|
                vb.customize ["modifyvm", :id, "--nicpromisc#{i+1}", "allow-all"]
            end
        end
    end

    # 
    # Ubntu
    # ------------------------------------------------------------
    host1 = "clos-host1"
    config.vm.define host1 do |host|
        host.vm.hostname = host1
        host.vm.box = 'bento/ubuntu-20.04'

        # private network config
        host.vm.network "private_network", virtualbox__intnet: "net3", auto_config: false

        host.vm.provision "shell", inline: $host1_conf

        # virtual box config
        host.vm.provider "virtualbox" do |vb|
            vb.name = host1
            vb.gui = $gui
            vb.cpus = 1
            vb.memory = 1024
            vb.customize [
                "modifyvm", :id,
                "--vram", "16", 
                "--clipboard", "bidirectional",
                "--draganddrop", "bidirectional",
                "--ioapic", "on",
                "--graphicscontroller", "vmsvga",
                "--accelerate3d", "off",
                "--hwvirtex", "on",
                "--nestedpaging", "on",
                "--largepages", "on",
                "--pae", "on",
                "--audio", "none",
                "--chipset", "ich9",
                "--uartmode1", "disconnected",
                "--description", $description
            ]

            (1..host.vm.networks.count {|nw| !nw.include? :forwarded_port}).each do |i|
                vb.customize ["modifyvm", :id, "--nicpromisc#{i+1}", "allow-all"]
            end
        end
    end

    host2 = "clos-host2"
    config.vm.define host2 do |host|
        host.vm.hostname = host2
        host.vm.box = 'bento/ubuntu-20.04'

        # private network config
        host.vm.network "private_network", virtualbox__intnet: "net4", auto_config: false

        host.vm.provision "shell", inline: $host2_conf

        # virtual box config
        host.vm.provider "virtualbox" do |vb|
            vb.name = host2
            vb.gui = $gui
            vb.cpus = 1
            vb.memory = 1024
            vb.customize [
                "modifyvm", :id,
                "--vram", "16", 
                "--clipboard", "bidirectional",
                "--draganddrop", "bidirectional",
                "--ioapic", "on",
                "--graphicscontroller", "vmsvga",
                "--accelerate3d", "off",
                "--hwvirtex", "on",
                "--nestedpaging", "on",
                "--largepages", "on",
                "--pae", "on",
                "--audio", "none",
                "--chipset", "ich9",
                "--uartmode1", "disconnected",
                "--description", $description
            ]

            (1..host.vm.networks.count {|nw| !nw.include? :forwarded_port}).each do |i|
                vb.customize ["modifyvm", :id, "--nicpromisc#{i+1}", "allow-all"]
            end
        end
    end
end
